In [16]:
import pandas as pd

In [17]:
df = pd.read_excel('patient-medical-records-2024.xlsx')
df

,admissions.case_year,admissions.hash,admissions.id,exams.age,exams.age_unit,exams.attitude,exams.bcs,exams.body,exams.cardiopulmonary,exams.cns,...,people.notes,people.organization,people.phone,people.postal_code,people.subdivision,species.class,species.family,species.genus,species.order,species.species
0,2024,NaN,1,NaN,Adult,Alert,Reasonable,NaN,NaN,NaN,...,NaN,NaN,5.714392e+09,20117,VA,Mammalia,Vespertilionidae,Eptesicus,Chiroptera,fuscus
1,2024,NaN,2,NaN,Adult,Quiet,Reasonable,NaN,NaN,No grip in R foot,...,NaN,NaN,5.404543e+09,20198,VA,Aves,Fringillidae,Spinus,Passeriformes,tristis
2,2024,NaN,3,NaN,Adult,Quiet,Reasonable,NaN,NaN,quiet,...,NaN,NaN,7.034302e+09,20176,VA,Aves,Accipitridae,Buteo,Accipitriformes,lineatus
3,2024,NaN,4,NaN,Adult,Quiet,Reasonable,NaN,"crackles in lungs, susp blood and windowstrike",NaN,...,NaN,NaN,7.038019e+09,22655,VA,Aves,Emberizidae,Junco,Passeriformes,hyemalis
4,2024,NaN,5,NaN,Adult,Alert,Good,NaN,dyspneic,NaN,...,NaN,NaN,5.714170e+09,20175,VA,Aves,Picidae,Sphyrapicus,Piciformes,varius
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3312,2024,NaN,3311,NaN,Adult,Alert,Reasonable,NaN,NaN,NaN,...,NaN,NaN,5.406642e+09,22624,VA,Reptilia,Emydidae,Terrapene,Testudines,Carolina
3313,2024,NaN,3312,NaN,Juvenile,Quiet,Reasonable,NaN,"some increase respiratory rate after handling,...",NaN,...,NaN,NaN,7.208106e+09,20175,VA,Aves,Columbidae,Zenaida,Columbiformes,macroura
3314,2024,NaN,3313,NaN,Adult,Alert,Reasonable,NaN,NaN,NaN,...,NaN,NaN,7.038351e+09,20165,VA,Reptilia,Emydidae,Terrapene,Testudines,Carolina
3315,2024,NaN,3314,NaN,Juvenile,Alert,Reasonable,NaN,tachypneic after handling,NaN,...,NaN,NaN,5.405608e+09,22630,VA,Aves,Cardinalidae,Cardinalis,Passeriformes,cardinalis
3316,2024,NaN,3315,NaN,Juvenile,Quiet,Thin,"back end soaked in urine, matted fur, no HL fu...",NaN,NaN,...,NaN,NaN,7.039638e+09,20151,VA,Mammalia,Sciuridae,Tamias,Rodentia,striatus

In [18]:
df.columns

Index(['admissions.case_year', 'admissions.hash', 'admissions.id', 'exams.age',
       'exams.age_unit', 'exams.attitude', 'exams.bcs', 'exams.body',
       'exams.cardiopulmonary', 'exams.cns', 'exams.comments',
       'exams.dehydration', 'exams.examined_at', 'exams.examiner',
       'exams.forelimb', 'exams.gastrointestinal', 'exams.head',
       'exams.hindlimb', 'exams.integument', 'exams.mm_color',
       'exams.mm_texture', 'exams.musculoskeletal', 'exams.nutrition',
       'exams.sex', 'exams.temperature', 'exams.temperature_unit',
       'exams.treatment', 'exams.type', 'exams.weight', 'exams.weight_unit',
       'patient_locations.area', 'patient_locations.comments',
       'patient_locations.enclosure', 'patient_locations.moved_in_at',
       'patient_locations.where_holding', 'patients.address_found',
       'patients.admitted_at', 'patients.admitted_by', 'patients.band',
       'patients.carcass_saved', 'patients.care_by_rescuer',
       'patients.city_found', 'patients.clinical_signs',
       'patients.common_name', 'patients.county_found',
       'patients.criminal_activity', 'patients.custom_field_1',
       'patients.custom_field_2', 'patients.days_in_care',
       'patients.diagnosis', 'patients.disposition',
       'patients.disposition_county', 'patients.disposition_lat',
       'patients.disposition_lng', 'patients.disposition_location',
       'patients.disposition_subdivision', 'patients.dispositioned_at',
       'patients.dispositioned_by', 'patients.found_at', 'patients.keywords',
       'patients.lat_found', 'patients.lng_found', 'patients.microchip_number',
       'patients.morph', 'patients.name', 'patients.notes_about_rescue',
       'patients.reason_for_disposition', 'patients.reasons_for_admission',
       'patients.reference_number', 'patients.release_type',
       'patients.subdivision_found', 'patients.transfer_type',
       'patients.transported_by', 'people.address', 'people.alt_phone',
       'people.city', 'people.country', 'people.county', 'people.email',
       'people.entity', 'people.first_name', 'people.is_member',
       'people.is_volunteer', 'people.last_name', 'people.no_solicitations',
       'people.notes', 'people.organization', 'people.phone',
       'people.postal_code', 'people.subdivision', 'species.class',
       'species.family', 'species.genus', 'species.order', 'species.species'],
      dtype='object')

## Drop Rows where there is no geolocation information

In [19]:
df[['patients.address_found', 'patients.county_found', 'patients.city_found']]

,patients.address_found,patients.county_found,patients.city_found
0,1179 SR-712,Loudoun,Upperville
1,3250 Bust Head Rd,Fauquier,The Plains
2,Intersection of Greenway and Rt 7,Loudoun,Leesburg
3,109 Keverne Ct.,Frederick,Stephens City
4,21024 Fox Hollow Ln.,Loudoun,Leesburg
...,...,...,...
3312,225 Sister Chipmunk Ln,Frederick,Clearbrook
3313,20333 Tanager Place,Loudoun,Leesburg
3314,Found on a walking trail behind Dockside Terra...,Fairfax,Sterling
3315,297 Cedar Mtn. Ln.,Warren,Front Royal
3316,4723 Benjamin Cross Ct.,Fairfax,Chantilly

Some of the data in 'patients.address_found' is not useful for programatically determining lat long coordinates. We want to drop the rows where the address_found starts with a alphabetic character AND either lat_found or lng_found is null

In [20]:
# determine which rows have the 'patients.address_found' column starting with a non-numeric character 
# df[df['patients.address_found'].str[0].str.isnumeric() == True]
# Set the 'patients.address_found' column to null for these rows
df.loc[df['patients.address_found'].str[0].str.isnumeric() == False, 'patients.address_found'] = None

In [21]:
# Drop rows where the following columns are empty: 'patients.address_found', 'patients.lat_found', 'patients.long_found'
df = df.dropna(subset=['patients.address_found', 'patients.lat_found', 'patients.lng_found'], how='all')

## Convert Address to Geolocation
For rows where we have an address but no lat or long info

In [33]:
df[['patients.address_found', 'patients.lat_found', 'patients.lng_found']]

       patients.address_found  patients.lat_found  patients.lng_found
0                 1179 SR-712           38.988773          -77.885399
1           3250 Bust Head Rd           38.903220          -77.737960
3             109 Keverne Ct.           39.096801          -78.176600
4        21024 Fox Hollow Ln.           39.035731          -77.654560
5           1463 New Hope Rd.           38.077545          -78.896725
...                       ...                 ...                 ...
3312   225 Sister Chipmunk Ln                 NaN                 NaN
3313      20333 Tanager Place                 NaN                 NaN
3314                     None           39.040332          -77.354295
3315       297 Cedar Mtn. Ln.                 NaN                 NaN
3316  4723 Benjamin Cross Ct.                 NaN                 NaN

[2786 rows x 3 columns]

In [41]:
# Unchecked but general direction of code
import geopy
from geopy.geocoders import Nominatim

loc = Nominatim(user_agent="Geopy Library")
get_loc = loc.geocode(df['patients.address_found'])
print(get_loc.latitute, "\n")
print(get_loc.longitude)

GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=0+++++++++++++++++++1179+SR-712%0A1+++++++++++++3250+Bust+Head+Rd%0A3+++++++++++++++109+Keverne+Ct.%0A4++++++++++21024+Fox+Hollow+Ln.%0A5+++++++++++++1463+New+Hope+Rd.%0A+++++++++++++++++...+++++++++++%0A3312+++++225+Sister+Chipmunk+Ln%0A3313++++++++20333+Tanager+Place%0A3314+++++++++++++++++++++++None%0A3315+++++++++297+Cedar+Mtn.+Ln.%0A3316++++4723+Benjamin+Cross+Ct.%0AName%3A+patients.address_found%2C+Length%3A+2786%2C+dtype%3A+object&format=json&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dc07a9de0>: Failed to establish a new connection: [Errno 61] Connection refused'))

In [ ]:
# Drop rows where either lat_found or _lng_found is NaN
df = df.dropna(subset=['patients.lat_found', 'patients.lng_found'])

In [ ]:
df[p[]]

In [ ]:
df[['patients.lat_found', 'patients.lng_found']]

      patients.lat_found  patients.lng_found
48             38.831823       -7.752172e+01
75             39.034220       -7.740088e+01
174            39.501650       -7.801266e+01
183            38.841123       -7.792664e+07
186            39.039670       -7.791998e+07
...                  ...                 ...
3243           39.165549       -7.818914e+01
3265           39.030428       -7.750816e+01
3272           39.040514       -7.742277e+01
3300           39.086555       -7.813949e+01
3314           39.040332       -7.735429e+01

[122 rows x 2 columns]

In [37]:
df[['patients.address_found', 'patients.lat_found', 'patients.lng_found']]

       patients.address_found  patients.lat_found  patients.lng_found
0                 1179 SR-712           38.988773          -77.885399
1           3250 Bust Head Rd           38.903220          -77.737960
3             109 Keverne Ct.           39.096801          -78.176600
4        21024 Fox Hollow Ln.           39.035731          -77.654560
5           1463 New Hope Rd.           38.077545          -78.896725
...                       ...                 ...                 ...
3312   225 Sister Chipmunk Ln                 NaN                 NaN
3313      20333 Tanager Place                 NaN                 NaN
3314                     None           39.040332          -77.354295
3315       297 Cedar Mtn. Ln.                 NaN                 NaN
3316  4723 Benjamin Cross Ct.                 NaN                 NaN

[2786 rows x 3 columns]

In [42]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut
import time
from concurrent.futures import ThreadPoolExecutor

# Initialize geolocator with a custom timeout value (in seconds)
geolocator = Nominatim(user_agent="Geopy Library")

# Cache to store geocoded addresses (address as key, (lat, lng) as value) to avoid repeating 
cache = {}

# Function to geocode an address 
def geocode_address(address, retries=3, delay=2):
    """
    Geocode an address with retry logic and timeout handling.
    Includes caching to avoid re-geocoding the same address.
    
    param address: The address to geocode.
    param retries: Number of retries on timeout (default 3).
    param delay: Delay (in seconds) between retries (default 2).
    return: Tuple (latitude, longitude) or (None, None) if not found.
    """
    if address in cache:
        return cache[address]  # Return cached result
    
    for attempt in range(retries):
        try:
            # Attempt to geocode with a 5-second timeout
            location = geolocator.geocode(address, timeout=5)
            
            if location:
                # Cache the result for future use
                cache[address] = (location.latitude, location.longitude)
                return location.latitude, location.longitude
            else:
                return None, None
        
        except GeocoderTimedOut:
            time.sleep(delay)  # Sleep before retrying
        except Exception as e:
            time.sleep(delay)  # Sleep before retrying
    
    return None, None

# Function to process each row in the DataFrame and update coordinates
def process_row(index, row):
    address = row['patients.address_found']
    if pd.notna(address):  # Only geocode if address is not NaN
        lat, lng = geocode_address(address)
        return index, lat, lng
    return index, None, None

# Function to populate missing latitude and longitude in the DataFrame using multi-threading
def populate_missing_coordinates(df):
    with ThreadPoolExecutor(max_workers=10) as executor:
        results = list(executor.map(lambda row: process_row(*row), df.iterrows()))
        
    for index, lat, lng in results:
        if lat is not None and lng is not None:
            df.at[index, 'patients.lat_found'] = lat
            df.at[index, 'patients.lng_found'] = lng
    return df

# Call the function to update missing latitude and longitude
df = populate_missing_coordinates(df)

# Output the updated DataFrame
df

## Determine Which ones are Vehicle Collision Related

In [ ]:
df['patients.reasons_for_admission'].value_counts()

patients.reasons_for_admission
Cat attack                                       87
HBV                                              74
Abandoned                                        40
Dog attack                                       37
Unable to fly                                    36
                                                 ..
Found with legs malformed, unable to stand        1
Found in road, suspect HBV                        1
Newborn, found alone on driveway                  1
Found in middle of road, injured, suspect HBV     1
hanging in tree caught with fishing line          1
Name: count, Length: 2119, dtype: int64

In [ ]:
vehicle_collision_strings = ['HBV', 'Found in road, suspect HBV']

In [ ]:
df[df['patients.reasons_for_admission'].isin(vehicle_collision_strings)]

,admissions.case_year,admissions.hash,admissions.id,exams.age,exams.age_unit,exams.attitude,exams.bcs,exams.body,exams.cardiopulmonary,exams.cns,...,people.notes,people.organization,people.phone,people.postal_code,people.subdivision,species.class,species.family,species.genus,species.order,species.species
32,2024,NaN,33,NaN,Adult,Quiet,Plump,NaN,NaN,NaN,...,"brought VaOp to Judie Graham, Native Wildlife ...",Judie Graham,5.409032e+09,22553,VA,Mammalia,Didelphidae,Didelphis,Didelphimorphia,virginiana
267,2024,NaN,268,NaN,Adult,Stuporous,Thin,"L carapace completely crushed and gutted, drie...",NaN,NaN,...,NaN,Loudoun County Animal Services,7.037770e+09,20175,VA,Reptilia,Emydidae,Chrysemys,Testudines,Picta
1052,2024,NaN,1052,NaN,Adult,Depressed,Reasonable,"multiple cranial carapace fractures, bridge fr...",NaN,possible skull trauma,...,NaN,NaN,5.402778e+09,22620,VA,Reptilia,Emydidae,Terrapene,Testudines,Carolina
1080,2024,NaN,1080,NaN,Adult,Quiet,Reasonable,severe cranial carapace fx from midline to lef...,NaN,NaN,...,NaN,NaN,5.404652e+09,NaN,VA,Reptilia,Emydidae,Chrysemys,Testudines,Picta
1102,2024,NaN,1102,NaN,Adult,Alert,Reasonable,NaN,NaN,NaN,...,Fairfax Co APP brought to Pender.,Pender Exotics Veterinary Center,NaN,NaN,VA,Reptilia,Chelydridae,Chelydra,Testudines,Serpentina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3183,2024,NaN,3182,NaN,Sub-adult,Quiet,Reasonable,NaN,NaN,NaN,...,NaN,NaN,3.047036e+09,26704,WV,Reptilia,Emydidae,Terrapene,Testudines,Carolina
3196,2024,NaN,3195,NaN,Adult,Quiet,Good,L shaped cr carapace fx directly over R should...,NaN,NaN,...,NaN,NaN,6.812713e+09,26865,WV,Reptilia,Emydidae,Terrapene,Testudines,Carolina
3259,2024,NaN,3258,NaN,Adult,Stuporous,Good,"severe cranial carapace and skull/jaw fxs, nea...",NaN,NaN,...,NaN,NaN,NaN,NaN,VA,Reptilia,Chelydridae,Chelydra,Testudines,Serpentina
3280,2024,NaN,3279,NaN,Adult,Obtunded,Reasonable,fully crushed cranial carapace w/ complete sev...,NaN,NaN,...,NaN,NaN,7.039661e+09,22611,VA,Reptilia,Emydidae,Terrapene,Testudines,Carolina
3307,2024,NaN,3306,NaN,Adult,Stuporous,Reasonable,NaN,open mouth breathing. Able to visualize the le...,stuporous mentation and slight head tilt to th...,...,NaN,NaN,7.576468e+09,22642,VA,Reptilia,Emydidae,Terrapene,Testudines,Carolina